function [im_x,im_y] = projectToCamera( camera, XD, YD, ZD)
% Returns a camera frame x,y coord given a world point and the camera frame
% to project into.
z = camera.P(3,1) * XD ...
    + camera.P(3,2) * YD ...
    + camera.P(3,3) * ZD ...
    + camera.P(3,4);
im_y = round( (camera.P(2,1) * XD ...
    + camera.P(2,2) * YD ...
    + camera.P(2,3) * ZD ...
    + camera.P(2,4)) ./ z);
im_x = round( (camera.P(1,1) * XD ...
    + camera.P(1,2) * YD ...
    + camera.P(1,3) * ZD ...
    + camera.P(1,4)) ./ z);

end

